version: '3.5'
services:
  spark-master:
    image: bitnami/spark:3.1.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ./resources/data:/opt/data
  spark-worker-1:
    image: bitnami/spark:3.1.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./resources/data:/opt/data
  spark-worker-2:
    image: bitnami/spark:3.1.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./resources/data:/opt/data
